name: alex
description: Tools for managing Flutter applications.
homepage: https://github.com/innim/
repository: https://github.com/Innim/alex
issue_tracker: https://github.com/Innim/alex/issues

version: 1.8.0

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  archive: ^3.4.10
  args: ^2.3.0
  dart_openai: ">=1.9.91 <1.9.92"
  glob: ^2.0.1
  hive: ^2.2.3
  in_date_utils: ^1.2.0+2
  ini: ^2.1.0
  intl: ^0.17.0
  intl_generator: ^0.4.1
  list_ext: ^1.0.4
  logging: ^1.0.2
  meta: ^1.7.0
  open_url: ^2.0.0
  path: ^1.8.0
  plain_optional: ^1.0.0
  pub_updater: ^0.3.0
  pubspec_yaml_2: ^3.2.0
  recase: ^4.0.0
  tuple: ^2.0.0
  version: ^2.0.0
  xml: ^5.1.2
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.3.0
  build_verify: ^3.1.0
  build_version: ^2.1.1
  innim_lint: ^0.4.0
  mockito: ^5.0.6
  test: ^1.17.12

executables:
  alex:
