name: alex
description: Tools for managing Flutter applications.
homepage: https://github.com/innim/
repository: https://github.com/Innim/alex
issue_tracker: https://github.com/Innim/alex/issues

version: 0.3.4-dev.1

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  path: ^1.7.0
  args: ^1.6.0
  yaml: ^2.2.1
  xml: ^4.4.1
  ini: ^2.0.1
  recase: ^3.0.0
  version: ^1.2.0
  intl: ^0.16.1
  meta: ^1.2.2
  open_url: ^1.0.1
  list_ext: ^0.1.0
  pubspec_yaml: ^2.0.1
  plain_optional: ^0.1.3
  intl_translation: ^0.17.10

dev_dependencies:
  innim_lint: ^0.1.7

executables:
  alex:
