name: alex
description: Tools for managing Flutter applications.
homepage: https://github.com/innim/
repository: https://github.com/Innim/alex
issue_tracker: https://github.com/Innim/alex/issues

version: 0.1.0-dev.1

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  path: ^1.7.0
  args: ^1.6.0
  yaml: ^2.2.1
  version: ^1.2.0
  intl_translation: ^0.17.10

dev_dependencies:
  pedantic: ^1.9.0

executables:
  alex:

assets:
  -assets/commands/release/change_log.html