import 'package:alex/src/agents/command_index.dart';
import 'package:alex/src/agents/project_facts.dart';

/// Commands that are recommended for an agent or a script,
/// in the order they should be listed.
///
/// A command that is not found in the index is skipped,
/// so the list can't break the section.
const _kRecommendedCommands = <String>[
  'code check',
  'code gen',
  'l10n check_translations',
  'pubspec get',
];

/// Renders the section about alex for the agent instructions
/// of the project (`CLAUDE.md`, `AGENTS.md` and alike).
///
/// Everything in the section is derived from the project configuration
/// and the commands tree, so it can be regenerated at any time.
class SectionRenderer {
  const SectionRenderer._();

  /// Renders the section in Markdown.
  static String render({
    required ProjectFacts facts,
    required CommandIndex index,
    required String version,
  }) {
    final sb = StringBuffer()
      ..writeln('## alex')
      ..writeln()
      ..writeln('Generated by `alex agents init` (alex $version). '
          'Do not edit inside the markers: run the command again to update.')
      ..writeln()
      ..writeln(_intro)
      ..writeln()
      ..writeln('### Project')
      ..writeln();

    for (final line in facts.lines) {
      sb.writeln('- $line');
    }

    sb
      ..writeln()
      ..writeln('### Commands')
      ..writeln();

    for (final path in _kRecommendedCommands) {
      final command = index.filter(path.split(' '))?.runnable.firstOrNull;
      if (command == null) continue;

      final codes = command.exitCodes.entries
          .map((e) => '`${e.key}` - ${e.value}')
          .join('; ');

      sb.writeln('- `alex ${command.path}` - ${command.summary}'
          '${command.supportsJson ? ' Supports `--format=json`.' : ''}'
          '${codes.isNotEmpty ? ' Exit codes: $codes.' : ''}');
    }

    sb
      ..writeln('- Everything else: run `alex agents guide` '
          'for the full reference of the installed version.')
      ..writeln()
      ..writeln(_outro);

    return sb.toString().trim();
  }

  static const _intro =
      'This project is managed with [alex](https://pub.dev/packages/alex) - '
      'a CLI for releases, localization, code generation and quality gates. '
      'Prefer its commands over hand written shell: they already know the '
      'configuration below, so they handle FVM, pub workspaces, subprojects '
      'and the localization pipeline for you.';

  static const _outro =
      'Check the exit code of a command, do not parse its human readable '
      'output: `0` - success, `1` - the command could not do its job, '
      '`2` - an unexpected error, `64` - wrong usage. Commands that support '
      '`--format=json` print a single JSON object in stdout, '
      'everything else - including the update banner - goes to stderr.';
}

extension _FirstOrNullExtension<T> on List<T> {
  T? get firstOrNull => isEmpty ? null : first;
}
